spring:
  datasource:
    url: localhost
    driver-class-name: org.postgresql.Driver
    username: username
    password: password

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

learn:
  getwordstolearn:
    newWordsCount: 8
    repeatWordsRandomCount: 4
    repeatWordsElderCount: 4
    repeatWordsDifficultCount: 4