spring:
  datasource:
    url: localohost
    driver-class-name: org.postgresql.Driver
    username: username
    password: password

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml